// export const data = {
//     talent: {
//       id: "",
//       name: "Talent",
//       shortCode: "Ta",
//       colourHex: "#2fb56a",
//     },
//     music: {
//       id: "",
//       name: "Music",
//       shortCode: "Mu",
//       colourHex: "#231f20",
//     },
//     tech: {
//       id: "",
//       name: "Tech",
//       shortCode: "Te",
//       colourHex: "#d4d0ae",
//     },
//     dance: {
//       id: "",
//       name: "Dance",
//       shortCode: "Da",
//       colourHex: "#f16676",
//     },
//     sports: {
//       id: "",
//       name: "Sports",
//       shortCode: "Ss",
//       colourHex: "#ffcb05",
//     },
//     time: {
//       id: "",
//       name: "Time",
//       shortCode: "Ti",
//       colourHex: "#af5f88",
//     },
//     meditation: {
//       id: "",
//       name: "Meditation",
//       shortCode: "Me",
//       colourHex: "#bbe0ca",
//     },
//     freedom: {
//       id: "",
//       name: "Freedom",
//       shortCode: "Fr",
//       colourHex: "#0098d7",
//     },
//     truth: {
//       id: "",
//       name: "Truth",
//       shortCode: "Tr",
//       colourHex: "#3aab45",
//     },
//     justice: {
//       id: "",
//       name: "Justice",
//       shortCode: "Ju",
//       colourHex: "#496573",
//     },
//     independent: {
//       id: "",
//       name: "Independent",
//       shortCode: "In",
//       colourHex: "#f37043",
//     },
//     balance: {
//       id: "",
//       name: "Balance",
//       shortCode: "Ba",
//       colourHex: "#fcc6a9",
//     },
//     faith: {
//       id: "",
//       name: "Faith",
//       shortCode: "Fa",
//       colourHex: "#671d7a",
//     },
//     kindness: {
//       id: "",
//       name: "Kindness",
//       shortCode: "Ki",
//       colourHex: "#f6adcd",
//     },
//     love: {
//       id: "",
//       name: "Love",
//       shortCode: "Lo",
//       colourHex: "#bb141a",
//     },
//     family: {
//       id: "",
//       name: "Family",
//       shortCode: "Fa",
//       colourHex: "#38247c",
//     },
//     god: {
//       id: "",
//       name: "God",
//       shortCode: "Gd",
//       colourHex: "#ba8750",
//     },
//     animals: {
//       id: "",
//       name: "Animals",
//       shortCode: "An",
//       colourHex: "#968f40",
//     },
//     nature: {
//       id: "",
//       name: "Nature",
//       shortCode: "Na",
//       colourHex: "#88ac2e",
//     },
//     spirit: {
//       id: "",
//       name: "Spirit",
//       shortCode: "Sp",
//       colourHex: "#44c8f5",
//     },
//     soul: {
//       id: "",
//       name: "Soul",
//       shortCode: "So",
//       colourHex: "#c6006f",
//     },
//     health: {
//       id: "",
//       name: "Health",
//       shortCode: "He",
//       colourHex: "#ed1c24",
//     },
//     peace: {
//       id: "",
//       name: "Peace",
//       shortCode: "Pe",
//       colourHex: "#abe1fa",
//     },
//     earth: {
//       id: "",
//       name: "Earth",
//       shortCode: "Ea",
//       colourHex: "#905501",
//     },
//     wealth: {
//       id: "",
//       name: "Wealth",
//       shortCode: "We",
//       colourHex: "#034ea2",
//     },
//     wisdom: {
//       id: "",
//       name: "Wisdom",
//       shortCode: "Wi",
//       colourHex: "#785989",
//     },
//     knowledge: {
//       id: "",
//       name: "Knowledge",
//       shortCode: "Kn",
//       colourHex: "#ee3356",
//     },
//     strength: {
//       id: "",
//       name: "Strength",
//       shortCode: "St",
//       colourHex: "#939598",
//     },
//     courage: {
//       id: "",
//       name: "Courage",
//       shortCode: "Co",
//       colourHex: "#fec667",
//     },
//   };
  



export const data = {
  talent: { id: "", name: "Talent", shortCode: "Ta", colourHex: "#2fb56a" },
  music: { id: "", name: "Music", shortCode: "Mu", colourHex: "#231f20" },
  tech: { id: "", name: "Tech", shortCode: "Te", colourHex: "#d4d0ae" },
  dance: { id: "", name: "Dance", shortCode: "Da", colourHex: "#f16676" },
  sports: { id: "", name: "Sports", shortCode: "Ss", colourHex: "#ffcb05" },
  time: { id: "", name: "Time", shortCode: "Ti", colourHex: "#af5f88" },
  meditation: { id: "", name: "Meditation", shortCode: "Me", colourHex: "#bbe0ca" },
  freedom: { id: "", name: "Freedom", shortCode: "Fr", colourHex: "#0098d7" },
  truth: { id: "", name: "Truth", shortCode: "Tr", colourHex: "#3aab45" },
  justice: { id: "", name: "Justice", shortCode: "Ju", colourHex: "#496573" },
  independent: { id: "", name: "Independent", shortCode: "In", colourHex: "#f37043" },
  balance: { id: "", name: "Balance", shortCode: "Ba", colourHex: "#fcc6a9" },
  faith: { id: "", name: "Faith", shortCode: "Fa", colourHex: "#671d7a" },
  kindness: { id: "", name: "Kindness", shortCode: "Ki", colourHex: "#f6adcd" },
  love: { id: "", name: "Love", shortCode: "Lo", colourHex: "#bb141a" },
  family: { id: "", name: "Family", shortCode: "Fa", colourHex: "#38247c" },
  god: { id: "", name: "God", shortCode: "Gd", colourHex: "#ba8750" },
  animals: { id: "", name: "Animals", shortCode: "An", colourHex: "#968f40" },
  nature: { id: "", name: "Nature", shortCode: "Na", colourHex: "#88ac2e" },
  spirit: { id: "", name: "Spirit", shortCode: "Sp", colourHex: "#44c8f5" },
  soul: { id: "", name: "Soul", shortCode: "So", colourHex: "#c6006f" },
  health: { id: "", name: "Health", shortCode: "He", colourHex: "#ed1c24" },
  peace: { id: "", name: "Peace", shortCode: "Pe", colourHex: "#abe1fa" },
  earth: { id: "", name: "Earth", shortCode: "Ea", colourHex: "#905501" },
  wealth: { id: "", name: "Wealth", shortCode: "We", colourHex: "#034ea2" },
  wisdom: { id: "", name: "Wisdom", shortCode: "Wi", colourHex: "#785989" },
  knowledge: { id: "", name: "Knowledge", shortCode: "Kn", colourHex: "#ee3356" },
  strength: { id: "", name: "Strength", shortCode: "St", colourHex: "#939598" },
  courage: { id: "", name: "Courage", shortCode: "Co", colourHex: "#fec667" },
  creativity: { id: "", name: "Creativity", shortCode: "Cr", colourHex: "#a29bfe" },
  innovation: { id: "", name: "Innovation", shortCode: "In", colourHex: "#74b9ff" },
  resilience: { id: "", name: "Resilience", shortCode: "Re", colourHex: "#00cec9" },
  adaptability: { id: "", name: "Adaptability", shortCode: "Ad", colourHex: "#fab1a0" },
  compassion: { id: "", name: "Compassion", shortCode: "Cp", colourHex: "#e84393" },
  honesty: { id: "", name: "Honesty", shortCode: "Ho", colourHex: "#fdcb6e" },
  patience: { id: "", name: "Patience", shortCode: "Pa", colourHex: "#636e72" },
  loyalty: { id: "", name: "Loyalty", shortCode: "Ly", colourHex: "#d63031" },
  discipline: { id: "", name: "Discipline", shortCode: "Di", colourHex: "#55efc4" },
  humility: { id: "", name: "Humility", shortCode: "Hu", colourHex: "#fd79a8" },
  curiosity: { id: "", name: "Curiosity", shortCode: "Cu", colourHex: "#00b894" },
  ambition: { id: "", name: "Ambition", shortCode: "Am", colourHex: "#e17055" },
  persistence: { id: "", name: "Persistence", shortCode: "Pe", colourHex: "#e67e22" },
  gratitude: { id: "", name: "Gratitude", shortCode: "Gr", colourHex: "#2d3436" },
  empathy: { id: "", name: "Empathy", shortCode: "Em", colourHex: "#6c5ce7" },
  generosity: { id: "", name: "Generosity", shortCode: "Ge", colourHex: "#ffeaa7" },
  purpose: { id: "", name: "Purpose", shortCode: "Pu", colourHex: "#fd9644" },
  integrity: { id: "", name: "Integrity", shortCode: "In", colourHex: "#27ae60" },
  leadership: { id: "", name: "Leadership", shortCode: "Le", colourHex: "#8e44ad" },
  joy: { id: "", name: "Joy", shortCode: "Jo", colourHex: "#f39c12" },
  excellence: { id: "", name: "Excellence", shortCode: "Ex", colourHex: "#c0392b" },
  mindfulness: { id: "", name: "Mindfulness", shortCode: "Mi", colourHex: "#d35400" },
  unity: { id: "", name: "Unity", shortCode: "Un", colourHex: "#7f8c8d" },
  collaboration: { id: "", name: "Collaboration", shortCode: "Co", colourHex: "#27ae60" },
  dedication: { id: "", name: "Dedication", shortCode: "De", colourHex: "#2980b9" },
  adventure: { id: "", name: "Adventure", shortCode: "Ad", colourHex: "#16a085" },
  exploration: { id: "", name: "Exploration", shortCode: "Ex", colourHex: "#3498db" },
  trust: { id: "", name: "Trust", shortCode: "Tr", colourHex: "#8e44ad" },
  perseverance: { id: "", name: "Perseverance", shortCode: "Pe", colourHex: "#f39c12" },
  diversity: { id: "", name: "Diversity", shortCode: "Di", colourHex: "#e74c3c" },
  equality: { id: "", name: "Equality", shortCode: "Eq", colourHex: "#3498db" },
  inclusion: { id: "", name: "Inclusion", shortCode: "In", colourHex: "#f1c40f" },
  respect: { id: "", name: "Respect", shortCode: "Re", colourHex: "#7f8c8d" },
  // openMindness: { id: "", name: "Open-Mindness", shortCode: "Op", colourHex: "#16a085" },
  responsibility: { id: "", name: "Responsibility", shortCode: "Re", colourHex: "#2c3e50" },
  flexibility: { id: "", name: "Flexibility", shortCode: "Fl", colourHex: "#27ae60" },
  leadership: { id: "", name: "Leadership", shortCode: "Le", colourHex: "#2980b9" },
  strategy: { id: "", name: "Strategy", shortCode: "St", colourHex: "#d35400" },
  innovation: { id: "", name: "Innovation", shortCode: "In", colourHex: "#c0392b" },
  teamSpirit: { id: "", name: "Team Spirit", shortCode: "Te", colourHex: "#8e44ad" },
};