// export const data = {
//     talent: {
//       id: "",
//       name: "Talent",
//       shortCode: "Ta",
//       colourHex: "#2fb56a",
//     },
//     music: {
//       id: "",
//       name: "Music",
//       shortCode: "Mu",
//       colourHex: "#231f20",
//     },
//     tech: {
//       id: "",
//       name: "Tech",
//       shortCode: "Te",
//       colourHex: "#d4d0ae",
//     },
//     dance: {
//       id: "",
//       name: "Dance",
//       shortCode: "Da",
//       colourHex: "#f16676",
//     },
//     sports: {
//       id: "",
//       name: "Sports",
//       shortCode: "Ss",
//       colourHex: "#ffcb05",
//     },
//     time: {
//       id: "",
//       name: "Time",
//       shortCode: "Ti",
//       colourHex: "#af5f88",
//     },
//     meditation: {
//       id: "",
//       name: "Meditation",
//       shortCode: "Me",
//       colourHex: "#bbe0ca",
//     },
//     freedom: {
//       id: "",
//       name: "Freedom",
//       shortCode: "Fr",
//       colourHex: "#0098d7",
//     },
//     truth: {
//       id: "",
//       name: "Truth",
//       shortCode: "Tr",
//       colourHex: "#3aab45",
//     },
//     justice: {
//       id: "",
//       name: "Justice",
//       shortCode: "Ju",
//       colourHex: "#496573",
//     },
//     independent: {
//       id: "",
//       name: "Independent",
//       shortCode: "In",
//       colourHex: "#f37043",
//     },
//     balance: {
//       id: "",
//       name: "Balance",
//       shortCode: "Ba",
//       colourHex: "#fcc6a9",
//     },
//     faith: {
//       id: "",
//       name: "Faith",
//       shortCode: "Fa",
//       colourHex: "#671d7a",
//     },
//     kindness: {
//       id: "",
//       name: "Kindness",
//       shortCode: "Ki",
//       colourHex: "#f6adcd",
//     },
//     love: {
//       id: "",
//       name: "Love",
//       shortCode: "Lo",
//       colourHex: "#bb141a",
//     },
//     family: {
//       id: "",
//       name: "Family",
//       shortCode: "Fa",
//       colourHex: "#38247c",
//     },
//     god: {
//       id: "",
//       name: "God",
//       shortCode: "Gd",
//       colourHex: "#ba8750",
//     },
//     animals: {
//       id: "",
//       name: "Animals",
//       shortCode: "An",
//       colourHex: "#968f40",
//     },
//     nature: {
//       id: "",
//       name: "Nature",
//       shortCode: "Na",
//       colourHex: "#88ac2e",
//     },
//     spirit: {
//       id: "",
//       name: "Spirit",
//       shortCode: "Sp",
//       colourHex: "#44c8f5",
//     },
//     soul: {
//       id: "",
//       name: "Soul",
//       shortCode: "So",
//       colourHex: "#c6006f",
//     },
//     health: {
//       id: "",
//       name: "Health",
//       shortCode: "He",
//       colourHex: "#ed1c24",
//     },
//     peace: {
//       id: "",
//       name: "Peace",
//       shortCode: "Pe",
//       colourHex: "#abe1fa",
//     },
//     earth: {
//       id: "",
//       name: "Earth",
//       shortCode: "Ea",
//       colourHex: "#905501",
//     },
//     wealth: {
//       id: "",
//       name: "Wealth",
//       shortCode: "We",
//       colourHex: "#034ea2",
//     },
//     wisdom: {
//       id: "",
//       name: "Wisdom",
//       shortCode: "Wi",
//       colourHex: "#785989",
//     },
//     knowledge: {
//       id: "",
//       name: "Knowledge",
//       shortCode: "Kn",
//       colourHex: "#ee3356",
//     },
//     strength: {
//       id: "",
//       name: "Strength",
//       shortCode: "St",
//       colourHex: "#939598",
//     },
//     courage: {
//       id: "",
//       name: "Courage",
//       shortCode: "Co",
//       colourHex: "#fec667",
//     },
//   };

export const data = {
  talent: { id: "", name: "Talent", shortCode: "Ta", colourHex: "#2fb56a" },
  music: { id: "", name: "Music", shortCode: "Mu", colourHex: "#231f20" },
  tech: { id: "", name: "Tech", shortCode: "Te", colourHex: "#d4d0ae" },
  dance: { id: "", name: "Dance", shortCode: "Da", colourHex: "#f16676" },
  sports: { id: "", name: "Sports", shortCode: "Ss", colourHex: "#ffcb05" },
  time: { id: "", name: "Time", shortCode: "Ti", colourHex: "#af5f88" },
  meditation: {
    id: "",
    name: "Meditation",
    shortCode: "Me",
    colourHex: "#bbe0ca",
  },
  freedom: { id: "", name: "Freedom", shortCode: "Fr", colourHex: "#0098d7" },
  truth: { id: "", name: "Truth", shortCode: "Tr", colourHex: "#3aab45" },
  justice: { id: "", name: "Justice", shortCode: "Ju", colourHex: "#496573" },
  independent: {
    id: "",
    name: "Independent",
    shortCode: "In",
    colourHex: "#f37043",
  },
  balance: { id: "", name: "Balance", shortCode: "Ba", colourHex: "#fcc6a9" },
  faith: { id: "", name: "Faith", shortCode: "Fa", colourHex: "#671d7a" },
  kindness: { id: "", name: "Kindness", shortCode: "Ki", colourHex: "#f6adcd" },
  love: { id: "", name: "Love", shortCode: "Lo", colourHex: "#bb141a" },
  family: { id: "", name: "Family", shortCode: "Fa", colourHex: "#38247c" },
  god: { id: "", name: "God", shortCode: "Gd", colourHex: "#ba8750" },
  animals: { id: "", name: "Animals", shortCode: "An", colourHex: "#968f40" },
  nature: { id: "", name: "Nature", shortCode: "Na", colourHex: "#88ac2e" },
  spirit: { id: "", name: "Spirit", shortCode: "Sp", colourHex: "#44c8f5" },
  soul: { id: "", name: "Soul", shortCode: "So", colourHex: "#c6006f" },
  health: { id: "", name: "Health", shortCode: "He", colourHex: "#ed1c24" },
  peace: { id: "", name: "Peace", shortCode: "Pe", colourHex: "#abe1fa" },
  earth: { id: "", name: "Earth", shortCode: "Ea", colourHex: "#905501" },
  wealth: { id: "", name: "Wealth", shortCode: "We", colourHex: "#034ea2" },
  wisdom: { id: "", name: "Wisdom", shortCode: "Wi", colourHex: "#785989" },
  knowledge: {
    id: "",
    name: "Knowledge",
    shortCode: "Kn",
    colourHex: "#ee3356",
  },
  strength: { id: "", name: "Strength", shortCode: "St", colourHex: "#939598" },
  courage: { id: "", name: "Courage", shortCode: "Co", colourHex: "#fec667" },
  creativity: {
    id: "",
    name: "Creativity",
    shortCode: "Cr",
    colourHex: "#a29bfe",
  },
  innovation: {
    id: "",
    name: "Innovation",
    shortCode: "In",
    colourHex: "#74b9ff",
  },
  resilience: {
    id: "",
    name: "Resilience",
    shortCode: "Re",
    colourHex: "#00cec9",
  },
  adaptability: {
    id: "",
    name: "Adaptability",
    shortCode: "Ad",
    colourHex: "#fab1a0",
  },
  compassion: {
    id: "",
    name: "Compassion",
    shortCode: "Cp",
    colourHex: "#e84393",
  },
  honesty: { id: "", name: "Honesty", shortCode: "Ho", colourHex: "#fdcb6e" },
  patience: { id: "", name: "Patience", shortCode: "Pa", colourHex: "#636e72" },
  loyalty: { id: "", name: "Loyalty", shortCode: "Ly", colourHex: "#d63031" },
  discipline: {
    id: "",
    name: "Discipline",
    shortCode: "Di",
    colourHex: "#55efc4",
  },
  humility: { id: "", name: "Humility", shortCode: "Hu", colourHex: "#fd79a8" },
  curiosity: {
    id: "",
    name: "Curiosity",
    shortCode: "Cu",
    colourHex: "#00b894",
  },
  ambition: { id: "", name: "Ambition", shortCode: "Am", colourHex: "#e17055" },
  persistence: {
    id: "",
    name: "Persistence",
    shortCode: "Pe",
    colourHex: "#e67e22",
  },
  gratitude: {
    id: "",
    name: "Gratitude",
    shortCode: "Gr",
    colourHex: "#2d3436",
  },
  empathy: { id: "", name: "Empathy", shortCode: "Em", colourHex: "#6c5ce7" },
  generosity: {
    id: "",
    name: "Generosity",
    shortCode: "Ge",
    colourHex: "#ffeaa7",
  },
  purpose: { id: "", name: "Purpose", shortCode: "Pu", colourHex: "#fd9644" },
  integrity: {
    id: "",
    name: "Integrity",
    shortCode: "In",
    colourHex: "#27ae60",
  },
  leadership: {
    id: "",
    name: "Leadership",
    shortCode: "Le",
    colourHex: "#8e44ad",
  },
  joy: { id: "", name: "Joy", shortCode: "Jo", colourHex: "#f39c12" },
  excellence: {
    id: "",
    name: "Excellence",
    shortCode: "Ex",
    colourHex: "#c0392b",
  },
  mindfulness: {
    id: "",
    name: "Mindfulness",
    shortCode: "Mi",
    colourHex: "#d35400",
  },
  unity: { id: "", name: "Unity", shortCode: "Un", colourHex: "#7f8c8d" },
  collaboration: {
    id: "",
    name: "Collaboration",
    shortCode: "Co",
    colourHex: "#27ae60",
  },
  dedication: {
    id: "",
    name: "Dedication",
    shortCode: "De",
    colourHex: "#2980b9",
  },
  adventure: {
    id: "",
    name: "Adventure",
    shortCode: "Ad",
    colourHex: "#16a085",
  },
  exploration: {
    id: "",
    name: "Exploration",
    shortCode: "Ex",
    colourHex: "#3498db",
  },
  trust: { id: "", name: "Trust", shortCode: "Tr", colourHex: "#8e44ad" },
  perseverance: {
    id: "",
    name: "Perseverance",
    shortCode: "Pe",
    colourHex: "#f39c12",
  },
  diversity: {
    id: "",
    name: "Diversity",
    shortCode: "Di",
    colourHex: "#e74c3c",
  },
  equality: { id: "", name: "Equality", shortCode: "Eq", colourHex: "#3498db" },
  inclusion: {
    id: "",
    name: "Inclusion",
    shortCode: "In",
    colourHex: "#f1c40f",
  },
  respect: { id: "", name: "Respect", shortCode: "Re", colourHex: "#7f8c8d" },
  // openMindness: { id: "", name: "Open-Mindness", shortCode: "Op", colourHex: "#16a085" },
  responsibility: {
    id: "",
    name: "Responsibility",
    shortCode: "Re",
    colourHex: "#2c3e50",
  },
  flexibility: {
    id: "",
    name: "Flexibility",
    shortCode: "Fl",
    colourHex: "#27ae60",
  },
  leadership: {
    id: "",
    name: "Leadership",
    shortCode: "Le",
    colourHex: "#2980b9",
  },
  strategy: { id: "", name: "Strategy", shortCode: "St", colourHex: "#d35400" },
  innovation: {
    id: "",
    name: "Innovation",
    shortCode: "In",
    colourHex: "#c0392b",
  },
  teamSpirit: {
    id: "",
    name: "Team Spirit",
    shortCode: "Te",
    colourHex: "#8e44ad",
  },
};

// Classic Core Values
export const classic = {
  authenticity: {
    id: "",
    name: "Authenticity",
    shortCode: "Au",
    colourHex: "#2fb56a",
  },
  family: { id: "", name: "Family", shortCode: "Fa", colourHex: "#38247c" },
  empathy: { id: "", name: "Empathy", shortCode: "Em", colourHex: "#6c5ce7" },
  unity: { id: "", name: "Unity", shortCode: "Un", colourHex: "#7f8c8d" },
  health: { id: "", name: "Health", shortCode: "He", colourHex: "#ed1c24" },
  duty: { id: "", name: "Duty", shortCode: "Du", colourHex: "#b80000" },
  discipline: {
    id: "",
    name: "Discipline",
    shortCode: "Di",
    colourHex: "#55efc4",
  },
  respect: { id: "", name: "Respect", shortCode: "Re", colourHex: "#7f8c8d" },
  workEthic: {
    id: "",
    name: "Work Ethic",
    shortCode: "Wo",
    colourHex: "#1abc9c",
  },
  creativity: {
    id: "",
    name: "Creativity",
    shortCode: "Cr",
    colourHex: "#a29bfe",
  },
  optimism: { id: "", name: "Optimism", shortCode: "Op", colourHex: "#f1c40f" },
  wisdom: { id: "", name: "Wisdom", shortCode: "Wi", colourHex: "#785989" },
  perseverance: {
    id: "",
    name: "Perseverance",
    shortCode: "Pe",
    colourHex: "#f39c12",
  },
  justice: { id: "", name: "Justice", shortCode: "Ju", colourHex: "#496573" },
  charity: { id: "", name: "Charity", shortCode: "Ch", colourHex: "#e74c3c" },
  faith: { id: "", name: "Faith", shortCode: "Fa", colourHex: "#671d7a" },
  inclusivity: {
    id: "",
    name: "Inclusivity",
    shortCode: "In",
    colourHex: "#f1c40f",
  },
  mindfulness: {
    id: "",
    name: "Mindfulness",
    shortCode: "Mi",
    colourHex: "#d35400",
  },
  independence: {
    id: "",
    name: "Independence",
    shortCode: "In",
    colourHex: "#f37043",
  },
  peace: { id: "", name: "Peace", shortCode: "Pe", colourHex: "#abe1fa" },
  kindness: { id: "", name: "Kindness", shortCode: "Ki", colourHex: "#f6adcd" },
  empowerment: {
    id: "",
    name: "Empowerment",
    shortCode: "Em",
    colourHex: "#00cec9",
  },
  integrity: {
    id: "",
    name: "Integrity",
    shortCode: "In",
    colourHex: "#27ae60",
  },
  dignity: { id: "", name: "Dignity", shortCode: "Di", colourHex: "#c0392b" },
  courage: { id: "", name: "Courage", shortCode: "Co", colourHex: "#fec667" },
  generosity: {
    id: "",
    name: "Generosity",
    shortCode: "Ge",
    colourHex: "#ffeaa7",
  },
  community: {
    id: "",
    name: "Community",
    shortCode: "Co",
    colourHex: "#3498db",
  },
  gratitude: {
    id: "",
    name: "Gratitude",
    shortCode: "Gr",
    colourHex: "#2d3436",
  },
  compassion: {
    id: "",
    name: "Compassion",
    shortCode: "Cp",
    colourHex: "#e84393",
  },
  sustainability: {
    id: "",
    name: "Sustainability",
    shortCode: "Su",
    colourHex: "#16a085",
  },
  trust: { id: "", name: "Trust", shortCode: "Tr", colourHex: "#8e44ad" },
  loyalty: { id: "", name: "Loyalty", shortCode: "Ly", colourHex: "#d63031" },
  curiosity: {
    id: "",
    name: "Curiosity",
    shortCode: "Cu",
    colourHex: "#00b894",
  },
  innovation: {
    id: "",
    name: "Innovation",
    shortCode: "In",
    colourHex: "#74b9ff",
  },
  diversity: {
    id: "",
    name: "Diversity",
    shortCode: "Di",
    colourHex: "#e74c3c",
  },
  humility: { id: "", name: "Humility", shortCode: "Hu", colourHex: "#fd79a8" },
  accountability: {
    id: "",
    name: "Accountability",
    shortCode: "Ac",
    colourHex: "#dfe6e9",
  },
  forgiveness: {
    id: "",
    name: "Forgiveness",
    shortCode: "Fo",
    colourHex: "#fab1a0",
  },
  philanthropy: {
    id: "",
    name: "Philanthropy",
    shortCode: "Ph",
    colourHex: "#6c5ce7",
  },
  travel: { id: "", name: "Travel", shortCode: "Tr", colourHex: "#2980b9" },
  sports: { id: "", name: "Sports", shortCode: "Sp", colourHex: "#ffcb05" },
  music: { id: "", name: "Music", shortCode: "Mu", colourHex: "#231f20" },
  art: { id: "", name: "Art", shortCode: "Ar", colourHex: "#f39c12" },
  fitness: { id: "", name: "Fitness", shortCode: "Fi", colourHex: "#2ecc71" },
  nature: { id: "", name: "Nature", shortCode: "Na", colourHex: "#88ac2e" },
  reading: { id: "", name: "Reading", shortCode: "Re", colourHex: "#9b59b6" },
  fashion: { id: "", name: "Fashion", shortCode: "Fa", colourHex: "#c0392b" },
  film: { id: "", name: "Film", shortCode: "Fi", colourHex: "#e74c3c" },
  hustle: { id: "", name: "Hustle", shortCode: "Hu", colourHex: "#16a085" },
};

// Spark Core Values:
export const spark = {
  freedom: { id: "", name: "Freedom", shortCode: "Fr", colourHex: "#0098d7" },
  adventure: {
    id: "",
    name: "Adventure",
    shortCode: "Ad",
    colourHex: "#16a085",
  },
  success: { id: "", name: "Success", shortCode: "Su", colourHex: "#27ae60" },
  friendships: {
    id: "",
    name: "Friendships",
    shortCode: "Fr",
    colourHex: "#e84393",
  },
  resilience: {
    id: "",
    name: "Resilience",
    shortCode: "Re",
    colourHex: "#00cec9",
  },
  passion: { id: "", name: "Passion", shortCode: "Pa", colourHex: "#ff7675" },
  equality: { id: "", name: "Equality", shortCode: "Eq", colourHex: "#3498db" },
  humour: { id: "", name: "Humour", shortCode: "Hu", colourHex: "#fdcb6e" },
  respect: { id: "", name: "Respect", shortCode: "Re", colourHex: "#7f8c8d" },
  growth: { id: "", name: "Growth", shortCode: "Gr", colourHex: "#2ecc71" },
  sports: { id: "", name: "Sports", shortCode: "Sp", colourHex: "#ffcb05" },
  leadership: {
    id: "",
    name: "Leadership",
    shortCode: "Le",
    colourHex: "#8e44ad",
  },
  entrepreneurship: {
    id: "",
    name: "Entrepreneurship",
    shortCode: "En",
    colourHex: "#e67e22",
  },
  sincerity: {
    id: "",
    name: "Sincerity",
    shortCode: "Si",
    colourHex: "#d35400",
  },
  curiosity: {
    id: "",
    name: "Curiosity",
    shortCode: "Cu",
    colourHex: "#00b894",
  },
  selfExpression: {
    id: "",
    name: "Self-Expression",
    shortCode: "Se",
    colourHex: "#a29bfe",
  },
  technology: {
    id: "",
    name: "Technology",
    shortCode: "Te",
    colourHex: "#d4d0ae",
  },
  environmentalResponsibility: {
    id: "",
    name: "Environmental Responsibility",
    shortCode: "Er",
    colourHex: "#16a085",
  },
  art: { id: "", name: "Art", shortCode: "Ar", colourHex: "#f39c12" },
  music: { id: "", name: "Music", shortCode: "Mu", colourHex: "#231f20" },
  charity: { id: "", name: "Charity", shortCode: "Ch", colourHex: "#e74c3c" },
  love: { id: "", name: "Love", shortCode: "Lo", colourHex: "#bb141a" },
  empathy: { id: "", name: "Empathy", shortCode: "Em", colourHex: "#6c5ce7" },
  joy: { id: "", name: "Joy", shortCode: "Jo", colourHex: "#f39c12" },
  wisdom: { id: "", name: "Wisdom", shortCode: "Wi", colourHex: "#785989" },
  pets: { id: "", name: "Pets", shortCode: "Pe", colourHex: "#f7b731" },
  sustainability: {
    id: "",
    name: "Sustainability",
    shortCode: "Su",
    colourHex: "#1abc9c",
  },
  innovation: {
    id: "",
    name: "Innovation",
    shortCode: "In",
    colourHex: "#74b9ff",
  },
  adaptability: {
    id: "",
    name: "Adaptability",
    shortCode: "Ad",
    colourHex: "#fab1a0",
  },
  collaboration: {
    id: "",
    name: "Collaboration",
    shortCode: "Co",
    colourHex: "#27ae60",
  },
  mindfulness: {
    id: "",
    name: "Mindfulness",
    shortCode: "Mi",
    colourHex: "#d35400",
  },
  positivity: {
    id: "",
    name: "Positivity",
    shortCode: "Po",
    colourHex: "#f1c40f",
  },
  balance: { id: "", name: "Balance", shortCode: "Ba", colourHex: "#fcc6a9" },
  integrity: {
    id: "",
    name: "Integrity",
    shortCode: "In",
    colourHex: "#27ae60",
  },
  justice: { id: "", name: "Justice", shortCode: "Ju", colourHex: "#496573" },
  hope: { id: "", name: "Hope", shortCode: "Ho", colourHex: "#3498db" },
  faith: { id: "", name: "Faith", shortCode: "Fa", colourHex: "#671d7a" },
  community: {
    id: "",
    name: "Community",
    shortCode: "Co",
    colourHex: "#3498db",
  },
  independence: {
    id: "",
    name: "Independence",
    shortCode: "In",
    colourHex: "#f37043",
  },
  gratitude: {
    id: "",
    name: "Gratitude",
    shortCode: "Gr",
    colourHex: "#2d3436",
  },
  service: { id: "", name: "Service", shortCode: "Se", colourHex: "#2980b9" },
  loyalty: { id: "", name: "Loyalty", shortCode: "Ly", colourHex: "#d63031" },
  family: { id: "", name: "Family", shortCode: "Fa", colourHex: "#38247c" },
  gaming: { id: "", name: "Gaming", shortCode: "Ga", colourHex: "#8e44ad" },
  reading: { id: "", name: "Reading", shortCode: "Re", colourHex: "#9b59b6" },
  travel: { id: "", name: "Travel", shortCode: "Tr", colourHex: "#2980b9" },
  film: { id: "", name: "Film", shortCode: "Fi", colourHex: "#e74c3c" },
  photography: {
    id: "",
    name: "Photography",
    shortCode: "Ph",
    colourHex: "#bdc3c7",
  },
  fitness: { id: "", name: "Fitness", shortCode: "Fi", colourHex: "#2ecc71" },
  fashion: { id: "", name: "Fashion", shortCode: "Fa", colourHex: "#c0392b" },
  hustle: { id: "", name: "Hustle", shortCode: "Hu", colourHex: "#16a085" },
};

// Bright Core Values:
export const bright = {
  smiles: { id: "", name: "Smiles", shortCode: "Sm", colourHex: "#ffbe76" },
  bravery: { id: "", name: "Bravery", shortCode: "Br", colourHex: "#e17055" },
  caringForAnimals: {
    id: "",
    name: "Caring for Animals",
    shortCode: "Ca",
    colourHex: "#badc58",
  },
  kindness: { id: "", name: "Kindness", shortCode: "Ki", colourHex: "#f6adcd" },
  sports: { id: "", name: "Sports", shortCode: "Sp", colourHex: "#ffcb05" },
  learning: { id: "", name: "Learning", shortCode: "Le", colourHex: "#00cec9" },
  manners: { id: "", name: "Manners", shortCode: "Ma", colourHex: "#d35400" },
  family: { id: "", name: "Family", shortCode: "Fa", colourHex: "#38247c" },
  playing: { id: "", name: "Playing", shortCode: "Pl", colourHex: "#81ecec" },
  imagination: {
    id: "",
    name: "Imagination",
    shortCode: "Im",
    colourHex: "#6c5ce7",
  },
  cooperation: {
    id: "",
    name: "Cooperation",
    shortCode: "Co",
    colourHex: "#27ae60",
  },
  crafts: { id: "", name: "Crafts", shortCode: "Cr", colourHex: "#f9ca24" },
  friends: { id: "", name: "Friends", shortCode: "Fr", colourHex: "#e84393" },
  toys: { id: "", name: "Toys", shortCode: "To", colourHex: "#f0932b" },
  teamwork: { id: "", name: "Teamwork", shortCode: "Tw", colourHex: "#74b9ff" },
  listening: {
    id: "",
    name: "Listening",
    shortCode: "Li",
    colourHex: "#a29bfe",
  },
  reading: { id: "", name: "Reading", shortCode: "Re", colourHex: "#9b59b6" },
  compassion: {
    id: "",
    name: "Compassion",
    shortCode: "Cp",
    colourHex: "#e84393",
  },
  art: { id: "", name: "Art", shortCode: "Ar", colourHex: "#f39c12" },
  cartoons: { id: "", name: "Cartoons", shortCode: "Ca", colourHex: "#f7b731" },
  playingOutside: {
    id: "",
    name: "Playing Outside",
    shortCode: "Po",
    colourHex: "#55efc4",
  },
  dance: { id: "", name: "Dance", shortCode: "Da", colourHex: "#f16676" },
  tidiness: { id: "", name: "Tidiness", shortCode: "Ti", colourHex: "#ff7979" },
  stories: { id: "", name: "Stories", shortCode: "St", colourHex: "#ffbe76" },
  laughter: { id: "", name: "Laughter", shortCode: "La", colourHex: "#ff7675" },
  gentleness: {
    id: "",
    name: "Gentleness",
    shortCode: "Ge",
    colourHex: "#74b9ff",
  },
  holidays: { id: "", name: "Holidays", shortCode: "Ho", colourHex: "#fab1a0" },
  sharing: { id: "", name: "Sharing", shortCode: "Sh", colourHex: "#fdcb6e" },
  music: { id: "", name: "Music", shortCode: "Mu", colourHex: "#231f20" },
  happiness: {
    id: "",
    name: "Happiness",
    shortCode: "Ha",
    colourHex: "#fd79a8",
  },
  caringForNature: {
    id: "",
    name: "Caring for Nature",
    shortCode: "Cn",
    colourHex: "#badc58",
  },
  helping: { id: "", name: "Helping", shortCode: "He", colourHex: "#ff7979" },
  followingRules: {
    id: "",
    name: "Following Rules",
    shortCode: "Fr",
    colourHex: "#dfe6e9",
  },
  pets: { id: "", name: "Pets", shortCode: "Pe", colourHex: "#f7b731" },
  honesty: { id: "", name: "Honesty", shortCode: "Ho", colourHex: "#fdcb6e" },
  patience: { id: "", name: "Patience", shortCode: "Pa", colourHex: "#636e72" },
  safetyFirst: {
    id: "",
    name: "Safety First",
    shortCode: "Sf",
    colourHex: "#81ecec",
  },
  helpingYourParents: {
    id: "",
    name: "Helping Your Parents",
    shortCode: "Hp",
    colourHex: "#fab1a0",
  },
  caringForOthers: {
    id: "",
    name: "Caring for Others",
    shortCode: "Co",
    colourHex: "#c39bd3",
  },
  chores: { id: "", name: "Chores", shortCode: "Ch", colourHex: "#e67e22" },
  exploring: {
    id: "",
    name: "Exploring",
    shortCode: "Ex",
    colourHex: "#3498db",
  },
  cooking: { id: "", name: "Cooking", shortCode: "Co", colourHex: "#e74c3c" },
  swimming: { id: "", name: "Swimming", shortCode: "Sw", colourHex: "#00cec9" },
  playdates: {
    id: "",
    name: "Playdates",
    shortCode: "Pd",
    colourHex: "#a29bfe",
  },
  puzzles: { id: "", name: "Puzzles", shortCode: "Pu", colourHex: "#e17055" },
  plants: { id: "", name: "Plants", shortCode: "Pl", colourHex: "#27ae60" },
  adventures: {
    id: "",
    name: "Adventures",
    shortCode: "Ad",
    colourHex: "#16a085",
  },
  science: { id: "", name: "Science", shortCode: "Sc", colourHex: "#8e44ad" },
  mermaids: { id: "", name: "Mermaids", shortCode: "Me", colourHex: "#00cec9" },
  pirates: { id: "", name: "Pirates", shortCode: "Pi", colourHex: "#f0932b" },
};
