export const data = {
    talent: {
      id: "",
      name: "Talent",
      shortCode: "Ta",
      colourHex: "#2fb56a",
    },
    music: {
      id: "",
      name: "Music",
      shortCode: "Mu",
      colourHex: "#231f20",
    },
    tech: {
      id: "",
      name: "Tech",
      shortCode: "Te",
      colourHex: "#d4d0ae",
    },
    dance: {
      id: "",
      name: "Dance",
      shortCode: "Da",
      colourHex: "#f16676",
    },
    sports: {
      id: "",
      name: "Sports",
      shortCode: "Ss",
      colourHex: "#ffcb05",
    },
    time: {
      id: "",
      name: "Time",
      shortCode: "Ti",
      colourHex: "#af5f88",
    },
    meditation: {
      id: "",
      name: "Meditation",
      shortCode: "Me",
      colourHex: "#bbe0ca",
    },
    freedom: {
      id: "",
      name: "Freedom",
      shortCode: "Fr",
      colourHex: "#0098d7",
    },
    truth: {
      id: "",
      name: "Truth",
      shortCode: "Tr",
      colourHex: "#3aab45",
    },
    justice: {
      id: "",
      name: "Justice",
      shortCode: "Ju",
      colourHex: "#496573",
    },
    independent: {
      id: "",
      name: "Independent",
      shortCode: "In",
      colourHex: "#f37043",
    },
    balance: {
      id: "",
      name: "Balance",
      shortCode: "Ba",
      colourHex: "#fcc6a9",
    },
    faith: {
      id: "",
      name: "Faith",
      shortCode: "Fa",
      colourHex: "#671d7a",
    },
    kindness: {
      id: "",
      name: "Kindness",
      shortCode: "Ki",
      colourHex: "#f6adcd",
    },
    love: {
      id: "",
      name: "Love",
      shortCode: "Lo",
      colourHex: "#bb141a",
    },
    family: {
      id: "",
      name: "Family",
      shortCode: "Fa",
      colourHex: "#38247c",
    },
    god: {
      id: "",
      name: "God",
      shortCode: "Gd",
      colourHex: "#ba8750",
    },
    animals: {
      id: "",
      name: "Animals",
      shortCode: "An",
      colourHex: "#968f40",
    },
    nature: {
      id: "",
      name: "Nature",
      shortCode: "Na",
      colourHex: "#88ac2e",
    },
    spirit: {
      id: "",
      name: "Spirit",
      shortCode: "Sp",
      colourHex: "#44c8f5",
    },
    soul: {
      id: "",
      name: "Soul",
      shortCode: "So",
      colourHex: "#c6006f",
    },
    health: {
      id: "",
      name: "Health",
      shortCode: "He",
      colourHex: "#ed1c24",
    },
    peace: {
      id: "",
      name: "Peace",
      shortCode: "Pe",
      colourHex: "#abe1fa",
    },
    earth: {
      id: "",
      name: "Earth",
      shortCode: "Ea",
      colourHex: "#905501",
    },
    wealth: {
      id: "",
      name: "Wealth",
      shortCode: "We",
      colourHex: "#034ea2",
    },
    wisdom: {
      id: "",
      name: "Wisdom",
      shortCode: "Wi",
      colourHex: "#785989",
    },
    knowledge: {
      id: "",
      name: "Knowledge",
      shortCode: "Kn",
      colourHex: "#ee3356",
    },
    strength: {
      id: "",
      name: "Strength",
      shortCode: "St",
      colourHex: "#939598",
    },
    courage: {
      id: "",
      name: "Courage",
      shortCode: "Co",
      colourHex: "#fec667",
    },
  };
  